In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('iris')

In [4]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
#every features data is in number and species is in values
df['species'].unique()
#species hi predict karni hai

<ArrowStringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = df.drop('species',axis=1)
y = df['species']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
#we will use knn model
from sklearn.neighbors import KNeighborsClassifier

In [12]:
model_knn = KNeighborsClassifier(n_neighbors=5)

In [13]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [15]:
model_knn.score(X_test,y_test)

0.98

In [16]:
#if you are getting an accuracy 100% it means your model is going overfit 
#if you chnage parameters and it will affect your accuracy

In [17]:
#no we will use svm to get accuracy
from sklearn.svm import SVC

In [27]:
model_svm = SVC(gamma='auto')
#c is a punishment to points who are near boundary

In [22]:
model_svm.fit(X_train,y_train)

SVC(C=30, gamma='auto')

In [23]:
model_svm.score(X_test,y_test)

0.98

In [24]:
#if we change c, accuracy score will also get change so thats why we will use
#grid seeacrh cv
#it helps the model to avoid overfit

In [25]:
from sklearn.model_selection import GridSearchCV

In [28]:
classifier = GridSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear']
}, cv=5,return_train_score=False) 

#classifier is a hyperparameter tuning variable
#estimator is model_svm

In [30]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [31]:
classifier.cv_results_

{'mean_fit_time': array([0.00499172, 0.00232296, 0.00178752, 0.00185404, 0.00186563,
        0.00176773, 0.00228953, 0.00175004]),
 'std_fit_time': array([0.00147772, 0.00102621, 0.00027048, 0.0004101 , 0.00051665,
        0.00023949, 0.00065741, 0.00018193]),
 'mean_score_time': array([0.00332766, 0.00127635, 0.00146289, 0.00149431, 0.00132656,
        0.0014173 , 0.00194702, 0.0016304 ]),
 'std_score_time': array([0.00200075, 0.0001233 , 0.00051814, 0.00047154, 0.00031605,
        0.00045944, 0.00102377, 0.00078101]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [32]:
results = pd.DataFrame(classifier.cv_results_)

In [33]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004992,0.001478,0.003328,0.002001,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002323,0.001026,0.001276,0.000123,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.001788,0.000270,0.001463,0.000518,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.001854,0.000410,0.001494,0.000472,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.001866,0.000517,0.001327,0.000316,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.001768,0.000239,0.001417,0.000459,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.002290,0.000657,0.001947,0.001024,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.001750,0.000182,0.001630,0.000781,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [35]:
results[['param_C','param_kernel','mean_test_score']] #param is parameter

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [36]:
#thats means if your param_cv and kernel it will give best mean test score

In [ ]:
#now we will use random search cv
from sklearn.model_selection import RandomizedSearchCV

In [39]:
classifier_r = RandomizedSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear']
},n_iter = 4 ,cv=5,return_train_score=False)

In [40]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [41]:
results2 = pd.DataFrame(classifier_r.cv_results_)

In [42]:
results2[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10       linear         0.973333
1        1       linear         0.980000
2       20       linear         0.966667
3        1          rbf         0.980000